services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: booklibrary-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  backend:
    build:
      context: ./backend
      dockerfile: BookLibrary.API/Dockerfile
    container_name: booklibrary-backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=BookLibraryDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False"
    depends_on:
      - db
    restart: on-failure
    ports:
      - "5046:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: booklibrary-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  sqlserver-data: